const types = {
  GET_LISTS_START: "GET_COMPANIES_START",
  GET_LISTS_SUCCESS: "GET_COMPANIES_SUCCESS",
  GET_LISTS_FAIL: "GET_COMPANIES_FAIL",
  CLEAR_LISTS_STORE: "CLEAR_COMPANIES_STORE",
  CHANGE_ACTIVE_COMPANY: "CHANGE_ACTIVE_COMPANY",
};

export default types;
