const types = {
  GET_LISTS_START: "GET_PRODUCTS_START",
  GET_LISTS_SUCCESS: "GET_PRODUCTS_SUCCESS",
  GET_LISTS_FAIL: "GET_PRODUCTS_FAIL",
  CLEAR_LISTS_STORE: "CLEAR_PRODUCTS_STORE",
  CHANGE_ACTIVE_COMPANY: "CHANGE_ACTIVE_PRODUCT",
};

export default types;
